### ISSUE TITLE
迭代计划 #2

### ISSUE THREAD

**Issue by chengluyu** [Kaiyiwing/qwerty-learner#101]
这是 #42 的后续，目前还未完成。

**开始时间：未定。**

### 🎨 UI/UX 相关

- [ ] 例句的 UI 设计及实现
- [ ] 一词多义的 UI 设计及实现
- [ ] 显示词性的 UI 设计及实现

待补充。

### 🐛 Bug 修复

待补充。

### 🔨 架构调整

待补充。

### 🐙 GitHub 相关

- [ ] 清理过期、无响应、内容不清晰的 issue
- [x] 打开 GitHub Discussion 供一般讨论使用
- [ ] 解决早于 2021 年 3 月 15 日的 PR

### 🛑 已推迟

暂无。

-----

@Kaiyiwing @sdu-gyf 欢迎直接编辑。
