### ISSUE TITLE
项目进展 #1

### ISSUE THREAD

**Issue by Kaiyiwing** [Kaiyiwing/qwerty-learner#42]
大家好，非常开心 Qwerty Learner 项目能够受到大家的喜欢  

通过 contributors 的努力，我们在开源之初的基础上增加与完善了许多功能，目前项目的基础体验已经相对完善，可以很好的满足大部分用户对一款单词记忆软件的需求。  

我们非常开心的宣布项目的第一个 iteration 圆满结束，我们会暂停一段时间功能性更新，仅对影响体验的 bug 进行修复。在这段时间内，我们会讨论项目未来功能的发展方向，我们非常希望大家能够通过 Issue 参与到讨论之中，给我们提供建议与想法。

## 开发任务
> 已经提上开发日程的工作

- [x] 代码重构 @Kaiyiwing 
- [x] 新版本UI更新 #23  @sdu-gyf 
- [x] 动画反馈 #6 @Kaiyiwing 
- [x] 单词发音  #34 pr: #50 @sdu-gyf @whexy 
- [x] 默写模式下输入错误时会显示音标提示 #55 @sdu-gyf 
- [x] 词典与章节选择框的UI更新 #45 @chengluyu 
- [x] Dark Mode #46 pr:#64 @CLDXiang

**Comment by gaoqiang19514** [comment]
打起来有点上瘾是怎么回事？

**Comment by gaoqiang19514** [comment]
可以上传自己的词库就好了

**Comment by wangzhengcheng1994** [comment]
这是一个很有意义的项目

**Comment by chengluyu** [comment]
春节将至，我们第一个迭代计划已经基本完成，感谢为所有在这一迭代计划中付出努力的朋友们。剩余的任务将会进入第二个迭代计划。祝大家春节快乐！ @Kaiyiwing @sdu-gyf @whexy @CLDXiang @BestDingSheng @SFAfreshman 

> As Chinese New Year approaches, the first iteration plan is completed, thanks to all those who had contributed in this period. The remaining and pending tasks will be moved into the second iteration. Happy Chinese New Year!

**Comment by Huaecase** [comment]
单词中的 横杠  -  怎么打？？？

**Comment by Kaiyiwing** [comment]
> 单词中的 横杠 - 怎么打？？？

直接用键盘上的 - 打就可以，注意切换英文输入法，如果还不行的话，告诉我一下词典和章节

**Comment by seassol** [comment]
shift alt  + q 是启动 怎么暂停呢？ 还望告知

**Comment by Kaiyiwing** [comment]
> shift alt  + q 是启动 怎么暂停呢？ 还望告知

也是shift alt q，是启动＋关闭键。
您的背诵进度会自动缓存在本地

**Comment by seassol** [comment]
@Kaiyiwing  感谢

**Comment by zzzmj** [comment]
请问有考虑增加导入自定义词书的功能吗（可以设定好一个数据格式，用户可自行导入）

**Comment by chengluyu** [comment]
@zzzmj 见 #75

**Comment by Jia1018** [comment]
请问这个网站可以在平板上使用吗？我试了一下好像不行…或者有没有考虑过做成应用程序呢？

**Comment by Kaiyiwing** [comment]
> 请问这个网站可以在平板上使用吗？我试了一下好像不行…或者有没有考虑过做成应用程序呢？

我们没有针对平板做过适配，但有用户反馈说 ipad ＋ 键盘是可以使用该软件的。
应用程序暂时没有计划，但我们非常欢迎社区的实现。

**Comment by hhxxttxs5628** [comment]
高中必修1，第8章里面，change one's mind 的单引号怎么打？可不可以加个“下一单词”的按钮？

**Comment by Kaiyiwing** [comment]
> 高中必修1，第8章里面，change one's mind 的单引号怎么打？可不可以加个“下一单词”的按钮？

是因为词典源中部分单词混入了中文符号，已修复 61630f2938bc54fee2e8ef0358534dd5b8e8f273

**Comment by Broogliu** [comment]
你好，可以把词性显示出来吗？

**Comment by niemj5** [comment]
您好，可以增加法语词典吗

**Comment by Kaiyiwing** [comment]
@niemj5 短期内应该不会添加，目前的贡献者里暂时没有法语的学习者

**Comment by ColarXu** [comment]
希望在每一章结束后，出现一个本章单词的汇总词汇表，然后可以把某些单词选进生词表，巩固练习。谢谢开发者，我很喜欢你的这个产品。

**Comment by notqueer** [comment]
当我选择完新章节再返回时，就会一直卡在加载界面，是浏览器的问题吗？

**Comment by notqueer** [comment]
我发现正常页面的网址是有qwerty-learner/这个路径的，返回时，这个路径就没了，就一直显示加载，又要重新加上

**Comment by JeanTheDreamer** [comment]
非常有意思的项目，谢谢各位开发者。想请问可以加PTE词库吗？PTE是目前比较流行的英文机器考试。再次感谢！

**Comment by N1nomiya** [comment]
> 非常有意思的项目，谢谢各位开发者。想请问可以加PTE词库吗？PTE是目前比较流行的英文机器考试。再次感谢！

@JeanTheDreamer  Yup! I desperately hope this can be merged! 😆
https://github.com/Kaiyiwing/qwerty-learner/pull/281

**Comment by 2636102433** [comment]
可以增加章节单词导出功能吗?可以导出本章节的所有词汇
能否增加关于python的新手基础词汇，目前较少

**Comment by Kaiyiwing** [comment]
python 词库目前主要是依赖于社区贡献

**Comment by SeanTandol** [comment]
可以增加错误单词巩固的词库吗，这样方便回溯

**Comment by cxzhou35** [comment]
可以开发相关的vim/neovim插件吗

**Comment by httogo** [comment]
那个键位提示可以做成动画放在下面吗，参考金山打字那种形式，直观地在屏幕上看到是那个键打错了，打到哪个键了，纠正键位感觉

**Comment by wanghuan12345678** [comment]
希望在单词下边加入单词常用的句子

**Comment by Num-10** [comment]
> 你好，可以把词性显示出来吗？

+1

**Comment by tsuzurux** [comment]
您好，想有一个能够去除已经很熟悉了的单词的功能。

**Comment by viazure** [comment]
请问 VSCode 扩展版的日语发音什么时候加上呀？

**Comment by zfyzmh** [comment]
希望加上GitHub登录多端同步数据

**Comment by Kaiyiwing** [comment]
> 今天第一次使用Qwerty Learner项目，非常惊人的背诵和肌肉记忆效率。 唯一迫切的是能否加入错词本，或者其他方式来集中背诵不熟练的单词

右上角有错题本

**Comment by GallenXun** [comment]
感谢答复，可能我表达的不明确，想表达的是一种类似其他comments说的，剔除熟悉单词，或集中练习不熟悉的功能。
个人理解是加入mark功能，单独生成一词库，不知道实现起来复不复杂
________________________________
发件人: Kaiyi ***@***.***>
发送时间: 2023年9月8日 21:09
收件人: Kaiyiwing/qwerty-learner ***@***.***>
抄送: GallenXun ***@***.***>; Comment ***@***.***>
主题: Re: [Kaiyiwing/qwerty-learner] 项目进展 #1 (#42)


今天第一次使用Qwerty Learner项目，非常惊人的背诵和肌肉记忆效率。 唯一迫切的是能否加入错词本，或者其他方式来集中背诵不熟练的单词

右上角有错题本

―

**Comment by sclszjx** [comment]
希望可以加入练习错题本的功能，love your work，thank you!

**Comment by lvbird** [comment]
感谢开发者。请问错题本的编辑功能(手动去除一些已经很熟悉的词)有考虑吗？

**Comment by RealKai42** [comment]
> 希望可以加入练习错题本的功能，love your work，thank you!

已经有这个功能了，在词书选择界面

**Comment by yiwenjinD** [comment]
建议注释里加入词性的区分

**Comment by qsjzxcpyy** [comment]
如果可以随时随地，遇到不懂的单词直接选中然后操作添加到词库就好了，自动查询单词词义

**Comment by Nosila-97** [comment]
可以把已经会的词语一键移除出词库吗
